const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    version: '1.0.0',
    title: 'My API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3003',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Todo',
      description: 'Endpoints',
    },
  ],
  definitions: {
    Todo: {
      status: 'todo',
      author: 'testauthor',
      description: 'testdescription',
      id: '6112ed7bd38071423dcd6f71',
    },
    AddTodo: {
      $author: 'testauthor',
      $description: 'testdescription',
    },
  },
}

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.ts']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./app.ts') // Your project's root file
})
